### ISSUE TITLE
Max interrupt frequency

### ISSUE THREAD

**Issue by albertfaromatics** [pjueon/JetsonGPIO#77]
What's the maximum interrupt frequency on a pin the library allows? I'm trying to control a DC motor with encoder, with an encoder frecuency of about 20KHz but I'm not achieving the expected results.

**Comment by pjueon** [comment]
Do you mean the frequency of the PWM? or just manually setting the pin to HIGH/LOW repeatedly?
I'm guessing you're not using PWM because I'm using jetson nano and I could get 40kHz and 60kHz with the PWM pin.
(This could be changed depending on your jetson model and the pin you're using.)

Anyway, I believe that the library doesn't intentionally limit the frequency at the software level. 
What does limit the frequency is probably the hardware. 

Of course, the implementation of the library could be optimized better but I don't believe that's gonna happen in the near feature.
